-- COMANDOS PARA CRIAR BANCO DE DADOS
CREATE DATABASE ESCOLA_BRUNO;

CREATE DATABASE ESCOLA_BRUNO2;

-- COMANDO PARA APAGAR BANCO DE DADOS
DROP DATABASE ESCOLA_BRUNO2;

-- COMANDO PARA ATIVAR BANCO DE DADOS
USE ESCOLA_BRUNO;

-- MOSTRAR TABELAS NO BANCO DE DADOS
SHOW TABLES;

-- COMANDO PARA CRIAR TABELAS
CREATE TABLE ALUNOS (
ID_ALUNO INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
RESPONSAVEL VARCHAR(60) NOT NULL,
RA_ESCOLA INT,
TURMA CHAR(10)
);

CREATE TABLE CLIENTES (
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
TELEFONE INT,
DATA_DE_NASCIMENTO DATE NOT NULL,
ENDERECO VARCHAR(60) NOT NULL
);

-- ALTERAR INFORMAÇÕES

ALTER TABLE ALUNOS ADD TELEFONE VARCHAR (15);

-- ALTERAR O TIPO DE DADOS E TAMANHO DO ATRIBUTO
ALTER TABLE ALUNOS MODIFY TELEFONE VARCHAR (15);

-- RENOMEAR O NOME DO ATRIBUTO
-- ALTER TABLE ALUNOS CHANGE TELEFONE CELULAR(15);

-- EXCLUIR ATRIBUTO
ALTER TABLE ALUNOS DROP COLUMN TELEFONE;

-- LIMPAR DADOS DA TABELA
TRUNCATE TABLE ALUNOS;